device: 'cuda:1'
task_name: "imu"
dataset: {
  data_dir: '/data2/EgoExo4D',
  annotations_file: './data/EgoExo4D/annotations_train.pkl',
  stream_labels: ["imu-left", "imu-right"],
  sensors: ["accl"],
  preload: True,
  mean: ./data/EgoExo4D/mean_std/accl_mean_left.pt,
  std: ./data/EgoExo4D/mean_std/accl_std_left.pt,
  normalize: False,
  visual: True,
  is_train: False
}
mean_std: {
  save_path: None,
}
spectrogram_params: {
  sec_2: {
    128x320: {
      downsampling_rate: 50,
      window_size: 2,
      n_fft: 256,
      win_length: 24,
      hop_length: 1,
      sampling_rate: 50,
      resizes: !!python/tuple [128, 320],
      temporal_points: 160
    }
  }
}
model: {
  name: 'mae_vit_base_patch',
  in_chans: 1,
  # embed_dim: 384,
  # depth: 12,
  # mask_ratio: 0.9,
  mask_2d: False,
  # mask_t_prob: 0.2,
  # mask_f_prob: 0.2,
  # mixup: 0.5,
  # drop_path: 0.1,
  # global_pool: True,
  # pretrain: False,
  use_custom_patch: False,
  # classification: False,
  alpha: 0.9,
  mode: 0,
  split_pos: False,
  pos_trainable: False,
  decoder_mode: 1,
  no_shift: False,
  use_nce: False,
  norm_pix_loss: False,
  audio_exp: False,
  128x320: {
    patch_size: !!python/tuple [16, 16],
  },
}